grafana:
  enabled: true
  service:
    portName: http
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - grafana.localdev
    tls:
      - hosts:
          - grafana.localdev
        secretName: grafana-tls

prometheus:
  prometheusSpec:
    retention: 2d
