apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami-store-0002
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/riheelh/argocd-rpi-demo.git
    targetRevision: HEAD
    path: apps/whoami/overlays/store-0002
  destination:
    server: https://kubernetes.default.svc
    namespace: store-0002
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
