apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/riheelh/argocd-rpi-demo.git
    targetRevision: HEAD
    path: apps/whoami/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: whoami-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true